name: Pull, build, push
on: 
  workflow_call:
    secrets:
      GHCR_USERNAME:
        required: true
      GHCR_TOKEN:
        required: true

jobs:        
  build:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.docker_build.outputs.imageFullName }}
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0

      - name: Build and push
        id: docker_build
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: ckb-explorer-api
          registry: ghcr.io
          # githubOrg: magickbase # optional
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
