name: Deploy to staging

on: 
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.docker_build.outputs.image }}
    steps:
      - name: Build and push
        id: docker_build
        uses: ./.github/workflows/k8s/build.yml 
        secrets: inherit
  deploy:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workload: [ckb-explorer-api, ckb-explorer-syncer, ckb-explorer-worker]
    steps:
      - uses: ./.github/workflows/k8s/update-image.yml 
        with:
          k8s-namespace: testnet
          k8s-workload: ${{ matrix.workload }}
          image: ${{ needs.build.outputs.image }}
        secrets: inherit
      - uses: ./.github/workflows/k8s/restart-workload.yml 
        with: 
          k8s-namespace: testnet
          k8s-workload: ${{ matrix.workload }}
        secrets: inherit


